apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
       - name: converter-container 
         image: us-central1-docker.pkg.dev/stellar-stream-452907-k9/python-converter-registry/converter-image:latest
         imagePullPolicy: Always
         ports:
          - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: converter-service
spec:
  selector:
    app: converter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: ClusterIP